language: python
python:
  - "2.7"

branches:
  only:
    - feature/casper
env:
  - DJANGO="1.4.x" DBENGINE=pg
  - DJANGO="1.5.x" DBENGINE=pg
  - DJANGO="1.6.x" DBENGINE=pg
  - DJANGO="dev" DBENGINE=pg

install:
  - export PATH=.:$PATH pip install coverage python-coveralls

script:
  - make init-db ci

before_script:
  - make init-db
  - "export DISPLAY=:99.0"
  - sleep 5
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - git clone git://github.com/n1k0/casperjs.git CASPERJS
  - ln -sf ${CASPERJS}/bin/casperjs ./casperjs

after_success:
  - coveralls -c .coveragerc

