language: python
python:
  - "2.7"

branches:
  only:
    - feature/casper
env:
  - DJANGO="1.4.x" DBENGINE=pg
  - DJANGO="1.5.x" DBENGINE=pg
  - DJANGO="1.6.x" DBENGINE=pg

install:
  - "export PATH=$PWD/~build/casperjs/bin:$PATH"
  - pip install coverage python-coveralls

script:
  - make ci

before_script:
  - make init-db install-casperjs
  - "export DISPLAY=:99.0"
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"


after_success:
  - coveralls -c .coveragerc

