language: python
python:
  - "2.6"
  - "2.7"
script: nosetests
env:
  - DJANGO_VERSION=1.4
install:
#  - pip install pep8 --use-mirrors
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r requirements.txt --use-mirrors

script: django-admin.py test adminactions --settings=adminactions.tests.settings
before_script:
#   - "pep8 --exclude=migrations --ignore=E501,E225 src"
