language: python
sudo: false
python:
  - 3.5

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOXENV=py27-d18
  - TOXENV=py27-d19
  - TOXENV=py27-d110
  - TOXENV=py27-d111
  - TOXENV=py27-dev

  - TOXENV=py33-d18
  - TOXENV=py33-dev

  - TOXENV=py34-d18
  - TOXENV=py34-dev

  - TOXENV=py35-d18
  - TOXENV=py35-d19
  - TOXENV=py35-d110
  - TOXENV=py35-d111
  - TOXENV=py35-dev

  - TOXENV=pypy-d18
  - TOXENV=pypy-d19
  - TOXENV=pypy-d110
  - TOXENV=pypy-d111
  - TOXENV=pypy-dev

matrix:
  allow_failures:
    - env: TOXENV=py35-dev
    - env: TOXENV=py27-dev
    - env: TOXENV=pypy-dev


install:
  - pip install -e ".[test]"

script:
  - tox -e $TOXENV -- py.test tests -vv --capture=no --cov=adminactions --cov-report= --cov-config=tests/.coveragerc

before_success:
  - coverage erase

after_success:
  - coverage combine
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/825f521b72e421171f8e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
