language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO="Django==1.4.5"
  - DJANGO="Django==1.5.1"
  - DJANGO="https://www.djangoproject.com/download/1.6b1/tarball/"

install:
  - pip install coverage python-coveralls
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  - coverage run django-admin.py test adminactions --settings=adminactions.tests.settings

after_success:
  - coveralls -c .coveragerc
