language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"

env:
  - DJANGO="Django==1.4.8"
  - DJANGO="Django==1.5.4"
  - DJANGO="https://www.djangoproject.com/download/1.6b4/tarball/"
  - DJANGO="git+https://github.com/django/django.git"

install:
  - pip install coverage python-coveralls
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  - make coverage

after_success:
  - coveralls -c .coveragerc

matrix:
  exclude:
    - python: 2.6
      env: DJANGO="git+https://github.com/django/django.git"
