language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION="Django==1.4.3"
  - DJANGO_VERSION="Django==1.5.1"
install:
  - pip install -q $DJANGO_VERSION
  - python setup.py -q install

script:
  - django-admin.py test adminactions --settings=adminactions.tests.settings
