language: python
python:
  - "2.7"

env:
  - DJANGO="1.4.x"
  - DJANGO="1.5.x"
  - DJANGO="1.6.x"
  - DJANGO="dev"

install:
  - pip install coverage python-coveralls
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  - make ci

after_success:
  - coveralls -c .coveragerc

matrix:
  exclude:
    - python: 2.6
      env: DJANGO="git+https://github.com/django/django.git"
