name: Python package

on:
    push:
        branches:
            - master

jobs:

    package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2

            - name: --
              run:  pip install check-manifest twine

            - name: Build Package
              run: check-manifest .

            - name: Build Package
              run: python setup.py sdist

            - name: Build Package
              run: |
                  twine check  dist/*

